### ISSUE TITLE
Rotary may get wrong status

### ISSUE THREAD

**Issue by ohmytime** [PE5PVB/TEF6686_multiband#1]
hello, 
in your KeyUp() and KeyDown()  function, I thought it may got wrong status , because in those functions, other code takes too many times before rotary get its position.

The result is,When going up, sometimes there is a downward movement

   ```
 if (optrot != 1) {
      while (digitalRead(ROTARY_PIN_A) == LOW || digitalRead(ROTARY_PIN_B) == LOW) {
        delay(5);
      }
    }

    position = encoder.getPosition();

```

I think the code snippet should be  ahead of other code in KeyUp() and KeyDown()

and V1  1.15 code is as well.

**Comment by PE5PVB** [comment]
This routine is just to prevent that behaviour. The while statement is to prevent bounces on cheap encoders. The position = encoder.getPosition(); is to reset the last received rotary encoder movement.

**Comment by ohmytime** [comment]
I mean you need to put the while statement in the very begging of KeyUp() and KeyDown function, 
I'v tested the result is very good.
While when you put that while statement in the last of function, it may sometimes  get wrong direction.

**Comment by PE5PVB** [comment]
Thanks for the tip

**Comment by ohmytime** [comment]
You're welcome.

Many thanks to your open source project, we have a lot of fun from it.
