### ISSUE TITLE
What has changed between this and the original?

### ISSUE THREAD

**Issue by veso266** [PE5PVB/TEF6686_multiband#2]
Hello there, I was wondering on what did you change between this version and the original: https://github.com/PE5PVB/TEF6686_ESP32

I mean, I can see you added an UHF frontend module, touchscreen and that the software is a bit reworked

But is this it? only the software and UHF frontend module?

I can also see that this (V2) has an option to stream bluetooth audio to the phone for instance, but can this be added on the original one with a modification of the software (ESP32 has bluetooth built in, so maybe its just a software thing)

Thanks for Anwsering and Best Regards

**Comment by PE5PVB** [comment]
Yes, main difference is control of the UHF board, added WiFi support, added support for bluetooth audio module and changed the display to Nextion. Also more advanced RDS decoder and menu settings. Ofcourse the layout of the PCB is different, see my website.

**Comment by veso266** [comment]
OK, if I understand you corecly, mostly software changes and different PCB layout

Hardware related are only Touchscreen, UHF board and extra bluetooth module (why extra module for audio if ESP32 already has bluetooth support?)

Just so you know what I am asking this wierd questions
I was thinking of buying a premade chinese clone: https://www.ebay.com/itm/155203689038?hash=item2422dc5a4e:g:sNUAAOSwA69jROlm&amdata=enc%3AAQAHAAAA4JJ0H67BHw1pHAzGM5fCicAjyYbMTD1kzUtOwtmLaZIsJkJ%2BBMsaJubxeq8dsoscB%2FSxy%2FEkbHfMEZ9xOvoWMcvCWVkSA%2BqGcWxeisWeipU9Kid%2BRHYHEKgTipgkGtCimkVDXx33QTXoVO3jnXBpARIVtBKTMPJnzPYqjrFgJvgrvTYfRVPpeLPxi3rlFv1rQ9KF9QZdmiYutonSKJR9XPX%2BPplfI7a0xlx18YU3%2FjsBKrvel2PxgjEFR%2FV7p7gmZ7LT0GCKfquREDxmRlS42IuQvfZSFUVh6kxzToAznIqz%7Ctkp%3ABFBMwNvJ2bZh

(I did ask for their schematics, I hope they give it to me :) )

and then just replace a touchscreen, and change TEF6686 with TEF6689 (they give you IQ data which is almost like an SDR)

They did not clone your V2 yet, so I am trying to improvize :smile:

**Comment by PE5PVB** [comment]
There were no IO's available for I2S audio. Second, the tuner cans do not provide I2S audio output, so in that case I had to implement the TEF chip on the PCB, which makes it very difficult for the majority to solder.

I don't know if the 6689 has IQ output. As far as I know it only has a capability to receive HD radio and ofcourse it has FMSI onboard. Where did you read about IQ output?

**Comment by veso266** [comment]
yea, smd is very hard to solder I once soldered some STM dev board called [Miško V3](https://www.youtube.com/watch?v=RF_qgmssy6U) together (although I only had to solder LEDs, some buttons and LCD cable it still took me 8hours (I destroyed 3 buttons, and 2leds that day, cuz everything was so small) (with help, and I had a magnifier glass) due to poor eye sight, so thats why I would like to simplify my life a bit (buy premade from china, modify later :smile: )

the chip doesn't do HD Radio and DRM nativly, but just provides you with data, that you can then use however your heart desires :smile:

If you check page 4 of datasheet: http://radio1.dxing.si/tef/datasheet.pdf

you will find DR_BCK, DR_WS, DR_Q_DATA, DR_I_DATA, DR_BLD (input used to blend the audio from external decoder, into TEFs audio) pins (that only TEF6688 and TEF6689 provide (I would go with TEF6689 cuz it also provides better FM Stereo decoding like 6687 does)

now if you read the user manual (or better said programing manual): http://radio1.dxing.si/tef/UserManualTEF6686.297261401.pdf

and go to page 46: 3.26 FM / AM cmd 84 Set_DR_Options, you will find it provides 650khz of IQ goodies for you to play with (a bit too much, maybe there is a way to lower this to something smaller, so ESP32 wouldn't suffer that much, but not sure)

**Comment by PE5PVB** [comment]
Sure, but it's only the IQ data from the received signal within the selected bandwidth. But usable for SSB or DRM demodulation. Please let me know when you played with the IQ data.

**Comment by veso266** [comment]
Hi, I think I finaly found where the chinese got the portable version from: 

Its this one which everyone is buying now: https://it.aliexpress.com/item/1005004590847337.html

https://twitter.com/fei666888/status/1498137873110814723?cxt=HHwWhsCi9aidusopAAAA

I am attaching a zip file containing the schematics (just in case this account gets banned) (yea it has wierd chinese file names which my computer cannot display but you have the gerber files as well as bom files with it as well)

I hope thats usefull to you (not sure if gerber files are editable, would realy love to change to touchscreen and replace TEF6686 with TEF6689 and route i2S audio to the MCU (so you could send audio over bluetooth), not sure if thats even possible :smile:
[TEF6686-Radio.zip](https://github.com/PE5PVB/TEF6686_multiband/files/10437846/TEF6686-Radio.zip)

I am still looking for the schematics for the LNA version: https://www.ebay.com/itm/155203689038
